import {
  onUpdateChange,
  onRedirect,
  onSubmit,
  onGoToAction,
  onGoToSelfServicePage,
  onResetIsUpdateActionExecuted,
  onGoBack,
  onGoToDashboard,
  onCompleteTask,
  onFilterChange,
  onResetPageOutput,
  onBackButtonCompleteTask,
  onRedirectToASHChecklist,
  onLogVideoMetrics
} from "./actions";
import {
  onStartApplication,
  onGetApplication,
  onLaunchFCRA,
  continueWithFCRADecline,
  createApplication,
  updateApplication,
  onSelectedShifts,
  onUpdateShiftSelection,
  onUpdateShiftSelectionSelfService,
  onCancelShiftSelectionSelfService,
  onGetCandidate,
  onTerminateApplication,
  onUpdateWotcStatus,
  onShowPreviousName,
  onSaveShiftPreferences
} from "./application-actions";
import {
  onGetRequisitionHeaderInfo,
  onGetNHETimeSlots,
  onGetPossibleNHEDates,
  onGetAllAvailableShifts,
  onGetAllAvailableShiftsSelfService,
  onGetChildRequisitions,
  onGetJobDescription,
  onGoToDescription,
  onApplyFilter,
  onApplyFilterSelfService,
  onResetFilters,
  onResetFiltersSelfService,
  onShiftsIncrementalLoad,
  onShiftsIncrementalLoadSelfService,
  selectJobRole,
  loadShiftPreferences
} from "./requisition-actions";

const actionMap: any = {
  ON_VALUE_CHANGE: onUpdateChange,
  ON_OUTPUT_VALUE_CHANGE: onUpdateChange,
  ON_REDIRECT: onRedirect,
  START_APPLICATION: onStartApplication,
  GET_REQUISITION_HEADER_INFO: onGetRequisitionHeaderInfo,
  SUBMIT_DATA: onSubmit,
  GET_APPLICATION: onGetApplication,
  LAUNCH_FCRA: onLaunchFCRA,
  CONTINUE_WITH_FCRA_DECLINE: continueWithFCRADecline,
  CREATE_APPLICATION: createApplication,
  UPDATE_APPLICATION: updateApplication,
  GET_NHE_TIME_SLOTS: onGetNHETimeSlots,
  GET_NHE_PREFERENCES_DATES: onGetPossibleNHEDates,
  GET_CHILD_REQUISITIONS: onGetChildRequisitions,
  GET_ALL_AVAILABLE_SHIFTS: onGetAllAvailableShifts,
  GET_ALL_AVAILABLE_SHIFTS_SELF_SERVICE: onGetAllAvailableShiftsSelfService,
  ON_GO_TO: onGoToAction,
  ON_GO_TO_SELF_SERVICE_PAGE: onGoToSelfServicePage,
  ON_GO_BACK: onGoBack,
  GO_TO_JOB_DESCRIPTION: onGoToDescription,
  UPDATE_SHIFT_SELECTION_SELF_SERVICE: onUpdateShiftSelectionSelfService,
  CANCEL_SHIFT_SELECTION_SELF_SERVICE: onCancelShiftSelectionSelfService,
  ON_SHIFT_SELECTION: onSelectedShifts,
  RESET_IS_UPDATE_ACTION_EXECUTED: onResetIsUpdateActionExecuted,
  GET_JOB_DESCRIPTION: onGetJobDescription,
  UPDATE_SHIFT_SELECTION: onUpdateShiftSelection,
  ON_GET_CANDIDATE: onGetCandidate,
  GO_TO_DASHBOARD: onGoToDashboard,
  TERMINATE_APPLICATION: onTerminateApplication,
  COMPLETE_TASK: onCompleteTask,
  UPDATE_WOTC_STATUS: onUpdateWotcStatus,
  ON_APPLY_FILTER: onApplyFilter,
  ON_APPLY_FILTER_SELF_SERVICE: onApplyFilterSelfService,
  RESET_FILTERS: onResetFilters,
  RESET_FILTERS_SELF_SERVICE: onResetFiltersSelfService,
  ON_FILTER_CHANGE: onFilterChange,
  ON_VALUE_UPDATE: onUpdateChange,
  ON_RESET_OUTPUT_STATE: onResetPageOutput,
  ON_BACK_BUTTON_COMPLETE_TASK: onBackButtonCompleteTask,
  SHOW_PREVIOUS_NAMES: onShowPreviousName,
  LOAD_INCREMENTAL_SHIFTS: onShiftsIncrementalLoad,
  LOAD_INCREMENTAL_SHIFTS_SELF_SERVICE: onShiftsIncrementalLoadSelfService,
  REDIRECT_TO_ASH_CHECKLIST: onRedirectToASHChecklist,
  SELECT_JOB_ROLE: selectJobRole,
  ON_SAVE_SHIFT_PREFERENCES: onSaveShiftPreferences,
  LOAD_SHIFT_PREFERENCES_DETAILS: loadShiftPreferences,
  LOG_VIDEO_METRICS: onLogVideoMetrics
};

export default actionMap;
