export enum EVENT {
  PAGE_LOAD = "page load",
  START_APPLICATION = "start application",
  START_ASSESSMENT = "assessment start",
  JOBS_FILTER = "jobs filter",
  JOBS_SORT = "jobs sort",
  SHIFT_SELECTED = "selected shift",
  GET_SHIFTS_ERROR = "shift display error",
  GET_SHIFTS_ERROR_SELF_SERVICE = "shift display error on self service page",
  CLICK_ROLE = "click role",
  SELECT_PREFERENCES = "select preferences",
  START_JOB_VIDEO = "start job video",
  FINISH_JOB_VIDEO = "finish job video",
  SUBMIT_NHE_PREFERENCES = "submit nhe preferences",
  RETURN_TO_NHE = "return to nhe",
  SELECT_NHE = "select NHE",
  NHE_PREFERENCE = "nhe preferences",
  GET_ALL_AVAILABLE_SHIFT_ERROR_SELF_SERVICE = "get all available shift error on self service page",
  NO_AVAILABLE_SHIFT_SELF_SERVICE = "no available shift on self service page",
  APPLY_FILTER_SELF_SERVICE = "apply filter on self service page",
  APPLY_SORTING_SELF_SERVICE = "apply sorting on self service page",
  SUCCESSFUL_UPDATE_SHIFT_SELF_SERVICE = "successfully update shift on self service page",
  SUCCESSFUL_CANCEL_SHIFT_SELF_SERVICE = "successfully cancel shift on self service page",
  FAIL_UPDATE_SHIFT_UNKNOWN_ERROR_SELF_SERVICE = "fail to update shift due to unknown error on self service page",
  FAIL_UPDATE_SHIFT_SCHEDULE_FULL_SELF_SERVICE = "fail to update shift due to full schedule on self service page",
  FAIL_UPDATE_SHIFT_UNSUCCESSFUL_REVERSION_SELF_SERVICE = "fail to update shift due to failed reversion on self service page",
  FAIL_CANCEL_SHIFT_SELF_SERVICE = "fail to cancel shift on self service page",
  SKIP_SCHEDULE_SELECTION = "skip schedule selection",
  THANK_YOU_SUBMIT = "submit on thank-you page",
  CANCELLATION_RESCHEDULE_REASON_SELF_SERVICE = "reason of cancellation or reschedule",
  NO_SSN_CONTINUE = "SSN continue",
  NO_SSN_CANCEL = "SSN cancel"
}

export enum PAGE_TYPE {
  APPLICATION = "application"
}

export const PAGE_NAME: any = {
  "pre-consent": "BB - welcome",
  "applicationId-null": "error - application id is undefined",
  consent: "job landing",
  "assessment-consent": "BB - pre-assessment",
  assessment: "BB - assessment",
  "assessment-finished": "BB - assessment finished",
  "job-opportunities": "Shift Select",
  "job-confirmation": "Shift Preview",
  "job-description": "job description",
  "job-roles": "job roles",
  "contingent-offer": "Accept Offer",
  bgc: "Fair Credit Report Act Disclosure",
  fcra: "Fair Credit Report Act Disclosure, Accept",
  nhe: "Schedule pre-hire appointment",
  "review-submit": "Review and Submit",
  "thank-you": "App Complete - Thank you for applying to Amazon",
  "self-identification": "Voluntary Self-Identification",
  wotc: "BB - WOTC",
  "supplementary-success": "supplementary forms thank you",

  "amazon-withdraws": "amazon-withdraws",
  "amazon-rejects": "amazon-rejects",
  "assessment-not-eligible": "assessment-not-eligible",
  "can-not-offer-job": "candidate-decline-FCRA",
  "candidate-withdraws": "candidate-withdraws",
  "rehire-not-eligible-seasonal-only": "rehire-not-eligible-seasonal-only",
  "rehire-not-eligible": "rehire-not-eligible",

  "no-available-shift": "no-shifts-available",
  "session-timeout": "session-timeout",

  "equal-opportunity-form": "Voluntary Self-Identification - Veteran Status",
  "veteran-status-form": "self ID: veteran status",
  "disability-form": "Voluntary Self-Identification - Disability Disclosure",

  "additional-bgc-info": "Additional Background Information",
  "non-fcra": "Non-Fair Credit Reporting Act Acknowledgments and Authorizations for Background Check",
  "cali-disclosure": "BGC: california disclosure",
  "job-preferences-thank-you": "shift preference submitted",
  "job-preferences": "shift preference",
  "nhe-preferences": "nhe preferences",

  "current-shift": "current-shift",
  "no-shift-selected": "no-shift-selected",
  "update-shift-confirmation": "update-shift-confirmation",
  "cancel-shift-confirmation": "cancel-shift-confirmation",
  "update-shift": "update-shift",
  "view-shift": "view-shift",

  "no-nhe-appointments": "NHE Unavailable"
};

export const PAGE_TITLE: Set<string> = new Set(
  [
    "already-applied",
    "applicationId-null",
    "pre-consent",
    "amazon-rejects",
    "amazon-withdraws",
    "assessment-consent",
    "assessment-not-eligible",
    "assessment",
    "bgc",
    "cali-disclosure",
    "can-not-offer-job",
    "candidate-withdraws",
    "consent",
    "contingent-offer",
    "fcra",
    "job-confirmation",
    "job-opportunities",
    "job-description",
    "job-roles",
    "nhe",
    "no-available-shift",
    "rehire-not-eligible-seasonal-only",
    "rehire-not-eligible",
    "review-submit",
    "self-identification",
    "session-timeout",
    "supplementary-success",
    "thank-you",
    "workflow-failed",
    "wotc",
    "job-preferences-thank-you",
    "job-preferences",
    "nhe-preferences"
  ],
);

export enum EVENT_NAMES {
  SUBMIT_NHE_PREFERENCES = "SUBMIT_NHE_PREFERENCES",
  SELECT_JOB_ROLE = "SELECT_JOB_ROLE",
  SELECT_NHE = "SELECT_NHE",
  SUBMIT_SHIFT_PREFERENCES = "SUBMIT_SHIFT_PREFERENCES"
};

export enum METRIC_NAME {
  PRE_CONSENT = "pre-consent",
  CONSENT = "consent",
  ASSESSMENT_CONSENT = "assessment-consent",
  ASSESSMENT_START = "assessment-start",
  ASSESSMENT_FINISHED = "assessment-finished",
  ASSESSMENT = "assessment",
  JOB_OPPORTUNITIES = "job-opportunities",
  JOB_ROLES = "job-roles",
  JOB_DESCRIPTION = "job-description",
  JOB_CONFIRMATION = "job-confirmation",
  START_SPECIFIC_JOB_VIDEO = "start-specific-job-video",
  FINISH_SPECIFIC_JOB_VIDEO = "finish-specific-job-video",
  CONTINGENT_OFFER = "contingent-offer",
  BGC = "bgc",
  NO_SSN_CONTINUE = "no-ssn-continue",
  NO_SSN_CANCEL = "no-ssn-cancel",
  FCRA = "fcra",
  NHE = "nhe",
  REVIEW_SUBMIT = "review-submit",
  THANK_YOU = "thank-you",
  SELF_IDENTIFICATION = "self-identification",
  WOTC = "wotc",
  SUPPLEMENTARY_SUCCESS = "supplementary-success",
  AMAZON_WITHDRAWS = "amazon-withdraws",
  AMAZON_REJECTS = "amazon-rejects",
  ASSESSMENT_NOT_ELIGIBLE = "assessment-not-eligible",
  CANDIDATE_WITHDRAWS = "candidate-withdraws",
  REHIRE_NOT_ELIGIBLE_SEASONAL_ONLY = "rehire-not-eligible-seasonal-only",
  REHIRE_NOT_ELIGIBLE = "rehire-not-eligible",
  CAN_NOT_OFFER_JOB = "can-not-offer-job",
  NO_AVAILABLE_SHIFT = "no-available-shift",
  NO_AVAILABLE_SHIFT_SELF_SERVICE = "no-available-shift-self-service",
  SUCCESSFUL_UPDATE_SHIFT_SELF_SERVICE = "successful-update-shift-self-service",
  FAIL_UPDATE_SHIFT_SCHEDULE_FULL_SELF_SERVICE = "fail-update-shift-schedule-full-self-service",
  FAIL_UPDATE_SHIFT_UNKNOWN_ERROR_SELF_SERVICE = "fail-update-shift-unknown-error-self-service",
  FAIL_UPDATE_SHIFT_SCHEDULE_UNSUCCESSFUL_REVERSION_SELF_SERVICE = "fail-update-shift-schedule-unsuccessful-reversion-self-service",
  SUCCESSFUL_CANCEL_SHIFT_SELF_SERVICE = "successful-cancel-shift-self-service",
  FAIL_CANCEL_SHIFT_SELF_SERVICE = "fail-cancel-shift-self-service",
  SESSION_TIMEOUT = "session-timeout",
  APPLICATION_ID_NULL = "applicationId-null",
  GET_ALL_AVALIABLE_SHIFT_ERROR = "get-all-avaliable-shift-error",
  GET_ALL_AVALIABLE_SHIFT_ERROR_SELF_SERVICE = "get-all-avaliable-shift-error-self-service",
  APPLY_FILTER_SELF_SERVICE = "apply-filter-self-service",
  APPLY_SORTING_SELF_SERVICE = "apply-sorting-self-service",
  APPLY_FILTER = "apply-filter",
  APPLY_SORTING = "apply-sorting",
  START_APPLICATION = "start-application",
  SHIFT_SELECTION = "shift-selection",
  EQUAL_OPPORTUNITY_FORM = "equal-opportunity-form",
  VETERAN_STATUS_FORM = "veteran-status-form",
  DISABILITY_FORM = "disability-form",
  ADDITIONAL_BGC_INFO = "additional-bgc-info",
  NON_FCRA = "non-fcra",
  CALI_DISCLOSURE = "cali-disclosure",
  JOB_PREFERENCES_THANK_YOU = "job-preferences-thank-you",
  JOB_PREFERENCES = "job-preferences",
  SELECT_JOB_ROLE = "SELECT_JOB_ROLE",
  SUBMIT_SHIFT_PREFERENCES = "SUBMIT_SHIFT_PREFERENCES",
  START_JOB_VIDEO = "start-job-video",
  FINISH_JOB_VIDEO = "finish-job-video",
  NHE_PREFERENCES = "nhe-preferences",
  SUBMIT_NHE_PREFERENCES = "SUBMIT_NHE_PREFERENCES",
  RETURN_TO_NHE = "RETURN_TO_NHE",
  SELECT_NHE = "SELECT_NHE",
  UPDATE_SHIFT = "update-shift",
  NO_SHIFT_SELECTED = "no-shift-selected",
  VIEW_SHIFT = "view-shift",
  CURRENT_SHIFT = "current-shift",
  CANCEL_SHIFT_CONFIRMATION = "cancel-shift-confirmation",
  UPDATE_SHIFT_CONFIRMATION = "update-shift-confirmation",
  SKIP_SCHEDULE = "skip-schedule",
  THANK_YOU_SUBMIT = "thank-you-submit",
  NO_AVAILABLE_TIME_SLOTS = "no-available-time-slots",
};
