import Loader from "./loader";
import {
  Action,
  AddressComponent,
  Button,
  Checkbox,
  CheckboxList,
  DatePicker,
  DaysHoursFilter,
  DetailedCheckbox,
  DetailedRadioButton,
  DetailedRadioButtonList,
  DisqualifiedQuestions,
  Dropdown,
  Expander,
  Html,
  IFrame,
  Image,
  JobRoleCard,
  JobRoleCardsList,
  Link,
  Markdown,
  MessageBanner,
  PageHeader,
  PageTitle,
  PhoneNumber,
  Popover,
  PreHireTask,
  RedirectButton,
  ShiftCard,
  ShiftCardsList,
  ScheduleCard,
  ScheduleCardsList,
  ShiftDetails,
  ScheduleDetails,
  ScheduleDetailPage,
  StatusLink,
  Steps,
  Text,
  TextAreaWithLength,
  TextBox,
  UL,
  Video
} from "@amzn/hvh-candidate-application-ui-components/lib";
import PanelContainer from "../containers/panel/panel-container";
import StepsContainer from "../containers/steps-content-renderer/index";
import FlyoutContainer from "../containers/flyout";
import StickyContentContainer from "../containers/sticky-content";
import ModalContainer from "../containers/modal/modal-container";
import ImageContainer from "./image";
import { Col, Row, Spacer, View } from "@amzn/stencil-react-components/layout";
import { Card as StencilCard } from "@amzn/stencil-react-components/card";

const ComponentMap: any = {
  loader: Loader,
  TextBox,
  Button,
  PageTitle,
  PhoneNumber,
  RedirectButton,
  Checkbox,
  CheckboxList,
  DisqualifiedQuestions,
  Text,
  PageHeader,
  Steps,
  DetailedCheckbox,
  StatusLink,
  Link,
  DetailedRadioButton,
  DetailedRadioButtonList,
  Action,
  Markdown,
  UL,
  Dropdown,
  DatePicker,
  MessageBanner,
  Panel: PanelContainer,
  Flyout: FlyoutContainer,
  Image,
  ImageContainer,
  Col,
  Row,
  Spacer,
  View,
  StencilCard,
  ShiftCard,
  ShiftCardsList,
  ScheduleCard,
  ScheduleCardsList,
  ShiftDetails,
  ScheduleDetails,
  ScheduleDetailPage,
  JobRoleCard,
  JobRoleCardsList,
  Html,
  Popover,
  StepsContainer,
  IFrame,
  Expander,
  PreHireTask,
  DaysHoursFilter,
  AddressComponent,
  TextAreaWithLength,
  Modal: ModalContainer,
  Video,
  StickyContent: StickyContentContainer
};

export default ComponentMap;
